Initial version for release
kirra/markdown-task-lists pull request #2
Opened 2019-10-04 12:07 UTC by doekenorg

2019-10-05 05:10 UTC, doekenorg commented
Needs a CHANGELOG.

2019-10-15 09:28 UTC, pharixces requested changes

2019-10-15 09:28 UTC, pharixces commented on src/TaskListsTrait.php
> +	 * {@inheritDoc}
A trait can be included in different files in different situations, inheritDoc would therefore inherit from different things, so you cannot use inheritDoc. Also; the {@inheritDoc} tag cannot be used in a summary, only in the description as inheritance is automatic.

@see https://docs.phpdoc.org/guides/inheritance.html

2019-10-15 09:28 UTC, pharixces commented on src/TaskListsTrait.php
> +	 * @marker [
This is a nonexisting tag according to the phpdoc specification.

2019-10-15 09:28 UTC, pharixces commented on .travis.yml
> +    - travis_retry php vendor/bin/php-coveralls
Add newline to the end of the file.

2019-10-15 09:35 UTC, doekenorg commented on src/TaskListsTrait.php
> +	 * @marker [
This is how it works.

2019-10-15 09:57 UTC, pharixces approved these changes

2019-10-15 09:57 UTC, merged